local utils = require('utils')
local options = { silent = true }

utils.map("n", "<A-,>", ":BufferPrevious<CR>", options)
utils.map("n", "<A-.>", ":BufferNext<CR>", options)
utils.map("n", "<A-<>", ":BufferMovePrevious<CR>", options)
utils.map("n", "<A->>", ":BufferMoveNext<CR", options)
utils.map("n", "<A-1>", ":BufferGoto 1<CR>", options)
utils.map("n", "<A-2>", ":BufferGoto 2<CR>", options)
utils.map("n", "<A-3>", ":BufferGoto 3<CR>", options)
utils.map("n", "<A-4>", ":BufferGoto 4<CR>", options)
utils.map("n", "<A-5>", ":BufferGoto 5<CR>", options)
utils.map("n", "<A-6>", ":BufferGoto 6<CR>", options)
utils.map("n", "<A-7>", ":BufferGoto 7<CR>", options)
utils.map("n", "<A-8>", ":BufferGoto 8<CR>", options)
utils.map("n", "<A-9>", ":BufferGoto 9<CR>", options)
utils.map("n", "<A-p>", ":BufferPin<CR>", options)
utils.map("n", "<A-c>", ":BufferClose<CR>", options)
utils.map("n", "<A-/>", ":BufferCloseAllButCurrent<CR>", options)
